server:
  port: 8761
   
spring:
  security:
    user:
      name: huaxia
      password: huaxia
   
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://huaxia:huaxia@localhost:8761/eureka/